# Generated by Django 3.1.3 on 2020-11-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogo', models.CharField(blank=True, max_length=255, null=True)),
                ('entrada', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('idioma', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('palavras_chaves', models.CharField(blank=True, max_length=255, null=True)),
                ('cobertura', models.CharField(blank=True, max_length=255, null=True)),
                ('estrutura', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_agregacao', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
