# Generated by Django 3.1.3 on 2020-11-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_geral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geral',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
