# Generated by Django 3.1.3 on 2020-11-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_auto_20201107_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='geral',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
