# Generated by Django 3.1.3 on 2020-11-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0008_auto_20201114_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geral',
            name='formato',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
    ]
