# Generated by Django 3.1.3 on 2020-11-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0010_auto_20201114_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geral',
            name='formato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geral',
            name='tamanho',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
