# Generated by Django 3.1.3 on 2020-11-20 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0012_auto_20201114_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=15, null=True, verbose_name='CPF/CNPJ')),
                ('contato', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contato')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'processos',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeServico', models.CharField(choices=[('SPA', 'Single Page Application'), ('PWA', 'Progressive Web Application'), ('WS', 'WebSite'), ('SW', 'Sistema Web'), ('IV', 'Identidade Visual')], max_length=4, verbose_name='Serviço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('Desconto', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Desconto')),
                ('parcelamento', models.IntegerField(choices=[(1, '01-A VISTA'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Parcelado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='processos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntrega', models.DateField(blank=True, null=True, verbose_name='Entrega')),
                ('status', models.IntegerField(choices=[(0, 'Iniciado'), (1, 'Em andamento'), (2, 'Pendente'), (3, 'Resolvido')], verbose_name='Status')),
                ('responsaveis', models.ManyToManyField(blank=True, null=True, related_name='responsaveis', to='processos.Cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Servicos', to='processos.servico')),
            ],
        ),
    ]
