# Generated by Django 3.1.3 on 2020-11-20 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0013_cliente_projeto_servico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
