# Generated by Django 3.1.3 on 2020-11-20 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0015_agregacao_cobertura_descricao_entrada_do_catalogo_estrutura_geral2_idioma_palavras_chave_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogo', models.CharField(blank=True, default='nulo', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.CharField(blank=True, default='nulo', max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='entrada_do_catalogo',
            name='catalogo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Catalogo', to='processos.catalogo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrada_do_catalogo',
            name='entrada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Entrada', to='processos.entrada'),
            preserve_default=False,
        ),
    ]
