# Generated by Django 3.1.3 on 2020-11-22 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0017_ciclo_de_vida_contribuição_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contribuição',
            new_name='Contribuicao',
        ),
        migrations.RenameField(
            model_name='contribuicao',
            old_name='contribuição',
            new_name='contribuicao',
        ),
    ]
