# Generated by Django 3.1.3 on 2020-11-22 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0019_auto_20201122_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(blank=True, default='nulo', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Formato', to='processos.formato')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tamanho', to='processos.tamanho')),
            ],
        ),
    ]
