# Generated by Django 3.1.3 on 2020-11-23 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0020_formato_tamanho_tecnico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geral',
        ),
    ]
