# Generated by Django 3.1.3 on 2020-11-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0021_delete_geral'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Geral2',
            new_name='Geral',
        ),
    ]
