# Generated by Django 3.1.3 on 2020-11-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0023_apioa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregacao',
            name='agregacao',
            field=models.IntegerField(blank=True, default='nulo', null=True),
        ),
    ]
