# Generated by Django 3.1.3 on 2020-11-25 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0024_auto_20201123_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='responsaveis',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
